# Generated by Django 2.2.5 on 2019-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20191111_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='content_type',
            new_name='content_type1',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='picture',
            new_name='picture1',
        ),
        migrations.AddField(
            model_name='ad',
            name='content_type2',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='picture2',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
