# Generated by Django 2.2.5 on 2019-11-13 21:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20191113_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('North Campus', 'North Campus'), ('Central Campus', 'Central Campus'), ('Other Area', 'Other Area')], max_length=38, null=True),
        ),
    ]
